-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.case_studies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  category text NOT NULL,
  subtitle text,
  challenge text,
  solution text,
  outcome text,
  excerpt text,
  image text,
  accent text DEFAULT 'emerald'::text,
  body jsonb DEFAULT '[]'::jsonb,
  featured boolean DEFAULT false,
  published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT case_studies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.team_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  role text NOT NULL,
  description text,
  image_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  sort_order integer NOT NULL DEFAULT 999,
  linkedin_url text,
  facebook_url text,
  instagram_url text,
  twitter_url text,
  upwork_url text,
  website_url text,
  CONSTRAINT team_members_pkey PRIMARY KEY (id)
);
CREATE TABLE public.case_study_team_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_study_id uuid NOT NULL,
  team_member_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT case_study_team_members_pkey PRIMARY KEY (id),
  CONSTRAINT case_study_team_members_case_study_id_fkey FOREIGN KEY (case_study_id) REFERENCES public.case_studies(id),
  CONSTRAINT case_study_team_members_team_member_id_fkey FOREIGN KEY (team_member_id) REFERENCES public.team_members(id)
);
CREATE TABLE public.team_page_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  title text NOT NULL,
  image_url text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  sort_order integer NOT NULL DEFAULT 999,
  published boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT team_page_members_pkey PRIMARY KEY (id)
);
CREATE TABLE public.meeting_gallery (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text,
  image_url text NOT NULL,
  sort_order integer NOT NULL DEFAULT 999,
  published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meeting_gallery_pkey PRIMARY KEY (id)
);
CREATE TABLE public.technology_logos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  image_url text NOT NULL,
  sort_order integer NOT NULL DEFAULT 999,
  published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT technology_logos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.partner_logos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name text NOT NULL,
  logo_image_url text,
  website_url text,
  sort_order integer DEFAULT 1,
  published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  image_url text,
  name text,
  CONSTRAINT partner_logos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.blog_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  category text NOT NULL,
  tags ARRAY DEFAULT '{}'::text[],
  author text DEFAULT 'GHL Prime Team'::text,
  excerpt text,
  cover_image text,
  reading_time integer,
  content text,
  seo_title text,
  seo_description text,
  seo_keywords text,
  featured boolean DEFAULT false,
  published boolean DEFAULT false,
  published_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT blog_posts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.showcase_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  origin_name text NOT NULL,
  origin_url text,
  origin_icon text,
  origin_description text,
  origin_tagline text,
  adaptation_badge text DEFAULT 'Enterprise Adaptation'::text,
  adaptation_name text NOT NULL,
  adaptation_description text,
  adaptation_tags jsonb DEFAULT '[]'::jsonb,
  sort_order integer NOT NULL DEFAULT 999,
  published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT showcase_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.showcase_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  value text NOT NULL,
  label text NOT NULL,
  sort_order integer NOT NULL DEFAULT 999,
  published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT showcase_stats_pkey PRIMARY KEY (id)
);
CREATE TABLE public.showcase_placements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_id uuid NOT NULL,
  page_key text NOT NULL,
  sort_order integer NOT NULL DEFAULT 999,
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT showcase_placements_pkey PRIMARY KEY (id),
  CONSTRAINT showcase_placements_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.showcase_items(id)
);
CREATE TABLE public.gallery_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  sort_order integer NOT NULL DEFAULT 999,
  published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gallery_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gallery_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text,
  image_url text NOT NULL,
  category_id uuid,
  sort_order integer NOT NULL DEFAULT 999,
  published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gallery_images_pkey PRIMARY KEY (id),
  CONSTRAINT gallery_images_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.gallery_categories(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  password_hash text NOT NULL,
  full_name text,
  role USER-DEFINED NOT NULL DEFAULT 'EDITOR'::"UserRole",
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.refresh_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  token_hash text NOT NULL,
  user_id uuid NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  revoked_at timestamp with time zone,
  user_agent text,
  ip_address text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.contact_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_name text,
  email text,
  phone text,
  company text,
  message text,
  source text,
  country text,
  role text,
  ghl_situation text,
  client_volume text,
  monthly_budget text,
  timeline text,
  biggest_challenge text,
  page_url text,
  status USER-DEFINED NOT NULL DEFAULT 'NEW'::"LeadStatus",
  notes text,
  submitted_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT contact_leads_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_surveys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  email text,
  phone text,
  business text,
  service text,
  source text,
  role text,
  business_type text,
  stage text,
  app_type text,
  needs text,
  budget text,
  sub_accounts text,
  lead_volume text,
  coverage text,
  details text,
  page_url text,
  status USER-DEFINED NOT NULL DEFAULT 'NEW'::"LeadStatus",
  notes text,
  submitted_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT service_surveys_pkey PRIMARY KEY (id)
);
CREATE TABLE public.media_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  public_id text NOT NULL,
  url text NOT NULL,
  secure_url text NOT NULL,
  format text,
  resource_type text,
  width integer,
  height integer,
  bytes integer,
  folder text,
  original_filename text,
  alt text,
  tags ARRAY DEFAULT ARRAY[]::text[],
  uploaded_by_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT media_assets_pkey PRIMARY KEY (id),
  CONSTRAINT media_assets_uploaded_by_id_fkey FOREIGN KEY (uploaded_by_id) REFERENCES public.users(id)
);
CREATE TABLE public.blog_ai_settings (
  id boolean NOT NULL DEFAULT true CHECK (id = true),
  instructions text NOT NULL DEFAULT ''::text,
  keywords text NOT NULL DEFAULT ''::text,
  advanced_instructions text NOT NULL DEFAULT ''::text,
  categories ARRAY NOT NULL DEFAULT ARRAY['GoHighLevel'::text, 'Automation'::text, 'AI Agents'::text, 'Case Studies'::text, 'Voice AI'::text, 'CRM'::text, 'Vibe Coding'::text],
  schedule_hour integer NOT NULL DEFAULT 6 CHECK (schedule_hour >= 0 AND schedule_hour <= 23),
  posts_per_day integer NOT NULL DEFAULT 1 CHECK (posts_per_day >= 1 AND posts_per_day <= 10),
  primary_provider text NOT NULL DEFAULT 'anthropic'::text CHECK (primary_provider = ANY (ARRAY['anthropic'::text, 'openai'::text])),
  fallback_enabled boolean NOT NULL DEFAULT false,
  anthropic_model text NOT NULL DEFAULT ''::text,
  openai_model text NOT NULL DEFAULT ''::text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  style_rules text NOT NULL DEFAULT 'Do not use em dashes. Write short, clear sentences aimed at a general reader. Avoid jargon. Prefer active voice.'::text,
  topic_focus_areas ARRAY NOT NULL DEFAULT ARRAY['AI automation'::text, 'CRM'::text, 'GoHighLevel'::text, 'Web Development'::text],
  review_window_minutes integer NOT NULL DEFAULT 20 CHECK (review_window_minutes >= 1 AND review_window_minutes <= 1440),
  image_generation_enabled boolean NOT NULL DEFAULT true,
  web_search_enabled boolean NOT NULL DEFAULT true,
  min_seo_score integer NOT NULL DEFAULT 70 CHECK (min_seo_score >= 0 AND min_seo_score <= 100),
  competitor_domains ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  max_internal_links integer NOT NULL DEFAULT 3 CHECK (max_internal_links >= 0 AND max_internal_links <= 10),
  blog_url_path text NOT NULL DEFAULT '/blog'::text,
  claude_cli_command text,
  codex_cli_command text,
  codex_enabled boolean NOT NULL DEFAULT false,
  placeholder_cover_image_url text NOT NULL DEFAULT ''::text,
  auto_blog_enabled boolean NOT NULL DEFAULT true,
  schedule_minute smallint NOT NULL DEFAULT 0,
  CONSTRAINT blog_ai_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.blog_ai_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider text NOT NULL CHECK (provider = ANY (ARRAY['anthropic'::text, 'openai'::text])),
  label text NOT NULL,
  token text NOT NULL,
  token_preview text NOT NULL,
  model text,
  enabled boolean NOT NULL DEFAULT true,
  status text NOT NULL DEFAULT 'idle'::text,
  cooldown_until timestamp with time zone,
  done_count integer NOT NULL DEFAULT 0,
  failed_count integer NOT NULL DEFAULT 0,
  last_used_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  auth_type text NOT NULL DEFAULT 'oauth'::text CHECK (auth_type = ANY (ARRAY['oauth'::text, 'api_key'::text])),
  CONSTRAINT blog_ai_accounts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.blog_ai_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status text NOT NULL CHECK (status = ANY (ARRAY['running'::text, 'success'::text, 'failed'::text])),
  provider text,
  account_label text,
  blog_post_id uuid,
  error text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  finished_at timestamp with time zone,
  alerted_at timestamp with time zone,
  current_step text,
  CONSTRAINT blog_ai_runs_pkey PRIMARY KEY (id),
  CONSTRAINT blog_ai_runs_blog_post_id_fkey FOREIGN KEY (blog_post_id) REFERENCES public.blog_posts(id)
);
CREATE TABLE public.blog_ai_drafts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['anthropic'::text, 'openai'::text])),
  title text NOT NULL,
  slug text NOT NULL,
  category text NOT NULL,
  primary_keyword text,
  tags ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  excerpt text NOT NULL DEFAULT ''::text,
  content text NOT NULL,
  seo_title text NOT NULL DEFAULT ''::text,
  seo_description text NOT NULL DEFAULT ''::text,
  seo_keywords text NOT NULL DEFAULT ''::text,
  reading_time integer,
  cover_image text,
  cover_image_alt text,
  topic_research jsonb,
  status text NOT NULL DEFAULT 'pending_review'::text CHECK (status = ANY (ARRAY['pending_review'::text, 'checking'::text, 'checker_failed'::text, 'approved'::text, 'rejected'::text, 'published'::text])),
  review_deadline timestamp with time zone NOT NULL,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  checker_result jsonb,
  blog_post_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT blog_ai_drafts_pkey PRIMARY KEY (id),
  CONSTRAINT blog_ai_drafts_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.blog_ai_runs(id),
  CONSTRAINT blog_ai_drafts_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id),
  CONSTRAINT blog_ai_drafts_blog_post_id_fkey FOREIGN KEY (blog_post_id) REFERENCES public.blog_posts(id)
);